Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -51,4 +51,6 @@ jobs:
         echo "Number of tests: $test_total"
     - name: Flag process as failed if any error or failure
       if: ${{ steps.ParseTestResults.outputs.test_failures!="0" || steps.ParseTestResults.outputs.test_errors!="0"}}
-      run: exit 1
+      run: | 
+        echo "Some tests are failing."
+        exit 1
